import crypto from "crypto";

const ALGORITHM = "aes-256-gcm";
const IV_LENGTH = 16;
const SALT_LENGTH = 64;
const TAG_LENGTH = 16;
const KEY_LENGTH = 32;

// In production, you MUST set ENCRYPTION_KEY in your .env
// It should be a 32-byte (256-bit) hex string or base64 string
function getEncryptionKey(): Buffer {
  const key = process.env.ENCRYPTION_KEY;
  if (!key) {
    if (process.env.NODE_ENV === "production") {
      throw new Error("ENCRYPTION_KEY environment variable is required in production");
    }
    // Fallback for local development only
    return crypto.scryptSync("bulkymailer-local-dev-key", "salt", KEY_LENGTH);
  }

  // If the key is provided as a hex string of exactly 64 characters (32 bytes)
  if (key.length === 64) {
    return Buffer.from(key, "hex");
  }

  // If it's base64 or any other string, we can hash it to ensure it's exactly 32 bytes
  // Or simply use scrypt to derive a stable 32-byte key from it
  return crypto.scryptSync(key, "bulkymailer-salt", KEY_LENGTH);
}

/**
 * Encrypts a plaintext string using AES-256-GCM.
 * Returns a hex-encoded string containing the iv, auth tag, and encrypted data.
 */
export function encrypt(text: string): string {
  if (!text) return "";

  const iv = crypto.randomBytes(IV_LENGTH);
  const key = getEncryptionKey();
  
  const cipher = crypto.createCipheriv(ALGORITHM, key, iv);
  
  let encrypted = cipher.update(text, "utf8", "hex");
  encrypted += cipher.final("hex");
  
  const authTag = cipher.getAuthTag().toString("hex");

  // Format: iv:authTag:encryptedText
  return `${iv.toString("hex")}:${authTag}:${encrypted}`;
}

/**
 * Decrypts an encrypted string previously generated by encrypt().
 */
export function decrypt(encryptedText: string): string {
  if (!encryptedText) return "";

  try {
    const parts = encryptedText.split(":");
    if (parts.length !== 3) {
      throw new Error("Invalid encrypted text format");
    }

    const iv = Buffer.from(parts[0], "hex");
    const authTag = Buffer.from(parts[1], "hex");
    const encrypted = parts[2];
    const key = getEncryptionKey();

    const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
    decipher.setAuthTag(authTag);

    let decrypted = decipher.update(encrypted, "hex", "utf8");
    decrypted += decipher.final("utf8");

    return decrypted;
  } catch (error) {
    console.error("[encryption_decrypt_error]", error);
    throw new Error("Failed to decrypt the value");
  }
}
